const router = require('express').Router();
const parentsRoutes = require('./parentsRoutes');
const requestRoutes = require('./requestRoutes');
const childrenRoutes = require('./childrenRoutes');
const nodemailerRoutes = require('./nodemailerRoutes');
router.use('/parents', parentsRoutes);
router.use('/children', childrenRoutes);
router.use('/request', requestRoutes);
router.use('/nodemailer', nodemailerRoutes);
module.exports = router;